### ISSUE TITLE
Deprecated router option

### ISSUE THREAD

**Issue by Valegar** [KnpLabs/KnpMailjetBundle#3]
The "pattern" option in file ".\vendor\knplabs\knp-mailjet-bundle\Knp\Bundle\MailjetBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.

**Comment by weaverryan** [comment]
Thanks @Valegar! I've fixed this and made the bundle compatible with 3.0. See version 1.1.0: https://github.com/KnpLabs/KnpMailjetBundle/releases/tag/1.1.0

**Comment by Valegar** [comment]
@weaverryan You're a star ;-)
